name: Build Polkadot Docker Image

on:
  pull_request:
    branches:
    - master

jobs:
  build-push-template:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Build Polkadot Docker Image
      uses: docker/build-push-action@v1 # https://github.com/docker/build-push-action
      with:
        push: false
        dockerfile: polkadot.Dockerfile
