name: Build and Publish Docker Images

on:
  push:
    branches:
    - master

jobs:
  build-push-polkadot:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Build Polkadot Docker Image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: polkadot.Dockerfile
        repository: joshyorndorff/cumulus-workshop-polkadot
        tags: latest
        add_git_labels: true
        tag_with_ref: true
        tag_with_sha: true

  build-push-parachain:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Build Parachain Template Docker Image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: parachain-collator.Dockerfile
        repository: joshyorndorff/cumulus-workshop-parachain-collator
        tags: latest
        add_git_labels: true
        tag_with_ref: true
        tag_with_sha: true
