name: Build and Publish Parachain Template Docker Image

on:
  push:
    branches:
    - master

jobs:
  build-push-template:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Build Parachain Template Docker Image
      uses: docker/build-push-action@v1 # https://github.com/docker/build-push-action
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: parachain-collator.Dockerfile
        repository: joshyorndorff/cumulus-workshop-parachain-collator
        tags: latest
        add_git_labels: true
        tag_with_ref: true
        tag_with_sha: true
